// src/components/Footer/Footer.vue
<script setup lang="ts">
withDefaults(defineProps<{
  companyName?: string;
  email?: string;
  address?: string;
}>(), {
  companyName: 'Zhong Yun Supply Chain Management Pte Ltd',
  email: 'support@diit-operation-platform.com',
  address: 'B-26-3A, MENARA G-VESTOR TOWER, KOMPLEKS PAVILION AMPANG, 200, JALAN AMPANG, 50450 KUALA LUMPUR.',
});

const currentYear = new Date().getFullYear();
</script>

<template>
  <footer class="footer" role="contentinfo">
    <div class="main">
      <div class="info-area">
        <div class="terms-column">
          <h4 class="section-title">条件与条款：</h4>
          <ul class="link-list">
            <li><a href="/privacy" class="link">隐私政策</a></li>
            <li><a href="/terms" class="link">服务条款</a></li>
            <li><a href="/returns" class="link">退换货政策</a></li>
          </ul>
        </div>

        <div class="contact-column">
          <h4 class="section-title">联系我们：</h4>
          <div class="contact-info">
            <div class="contact-row">
              <span class="label">名称：</span>
              <span>{{ companyName }}</span>
            </div>
            <div class="contact-row">
              <span class="label">邮箱：</span>
              <a :href="`mailto:${email}`" class="link">{{ email }}</a>
            </div>
            <div class="contact-row">
              <span class="label">地址：</span>
              <span class="address">{{ address }}</span>
            </div>
          </div>
        </div>
      </div>

      <div class="payment-icons" aria-label="应用下载">
        <a
          class="payment-icon"
          href="https://play.google.com/store"
          target="_blank"
          rel="noopener noreferrer"
          aria-label="在 Google Play 下载"
        >
          <img src="/assets/footer/google-play.png" alt="Google Play" />
        </a>
        <a
          class="payment-icon"
          href="https://apps.apple.com"
          target="_blank"
          rel="noopener noreferrer"
          aria-label="在 App Store 下载"
        >
          <img src="/assets/footer/app-store.png" alt="App Store" />
        </a>
      </div>
    </div>

    <div class="copyright">
      <p>© 版权所有 {{ currentYear }}，ECBclub保留所有权利。</p>
    </div>
  </footer>
</template>

<style scoped>
.footer {
  width: 100%;
  background: #F6F6F6;
}

.main {
  display: flex;
  justify-content: center;
  align-items: flex-start;
  gap: 171px;
  max-width: 1280px;
  margin: 0 auto;
  padding: 32px 0;
}

.info-area {
  display: flex;
  align-items: flex-start;
  gap: 72px;
}

.terms-column {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  gap: 24px;
  width: 87px;
}

.section-title {
  font-family: 'PingFang SC', sans-serif;
  font-weight: 400;
  font-size: 14px;
  line-height: 125%;
  color: #000;
  white-space: nowrap;
}

.link-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.link {
  font-family: 'PingFang SC', sans-serif;
  font-weight: 400;
  font-size: 14px;
  line-height: 125%;
  color: #FF7E21;
  text-decoration: underline;
  transition: opacity 0.2s ease;
}

.link:hover {
  opacity: 0.7;
}

.contact-column {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  gap: 24px;
}

.contact-info {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.contact-row {
  display: flex;
  align-items: flex-start;
  gap: 16px;
}

.label {
  font-family: 'PingFang SC', sans-serif;
  font-weight: 400;
  font-size: 14px;
  line-height: 125%;
  color: #888;
  white-space: nowrap;
  min-width: 42px;
}

.address {
  max-width: 418px;
  font-family: 'PingFang SC', sans-serif;
  font-weight: 400;
  font-size: 14px;
  line-height: 125%;
  color: #000;
}

.payment-icons {
  display: flex;
  flex-direction: column;
  gap: 20px;
  flex: none;
}

.payment-icon {
  width: 136px;
  height: 40px;
}

.payment-icon img {
  width: 100%;
  height: 100%;
  object-fit: contain;
}

.copyright {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 10px;
  border-top: 1px solid #E3E3E3;
  background: #F6F6F6;
}

.copyright p {
  font-family: 'Plus Jakarta Sans', sans-serif;
  font-weight: 400;
  font-size: 14px;
  line-height: 125%;
  color: #888;
}
</style>

// src/components/Footer/Footer.tsx
import styles from './Footer.module.css';

export interface FooterProps {
  /** 公司名称 */
  companyName?: string;
  /** 公司邮箱 */
  email?: string;
  /** 公司地址 */
  address?: string;
}

/**
 * Footer — 页脚组件
 * 布局: [条件与条款 | 联系我们] ← 171px → [支付图标×2]
 * 支付图标使用切图，放在 public/assets/footer/ 目录
 */
export function Footer({
  companyName = 'Zhong Yun Supply Chain Management Pte Ltd',
  email = 'support@diit-operation-platform.com',
  address = 'B-26-3A, MENARA G-VESTOR TOWER, KOMPLEKS PAVILION AMPANG, 200, JALAN AMPANG, 50450 KUALA LUMPUR.',
}: FooterProps) {
  const currentYear = new Date().getFullYear();

  return (
    <footer className={styles.footer} role="contentinfo">
      <div className={styles.main}>
        {/* 左侧：条款 + 联系 */}
        <div className={styles.infoArea}>
          {/* 条件与条款 */}
          <div className={styles.termsColumn}>
            <h4 className={styles.sectionTitle}>条件与条款：</h4>
            <ul className={styles.linkList}>
              <li>
                <a href="/privacy" className={styles.link}>隐私政策</a>
              </li>
              <li>
                <a href="/terms" className={styles.link}>服务条款</a>
              </li>
              <li>
                <a href="/returns" className={styles.link}>退换货政策</a>
              </li>
            </ul>
          </div>

          {/* 联系我们 */}
          <div className={styles.contactColumn}>
            <h4 className={styles.sectionTitle}>联系我们：</h4>
            <div className={styles.contactInfo}>
              <div className={styles.contactRow}>
                <span className={styles.label}>名称：</span>
                <span>{companyName}</span>
              </div>
              <div className={styles.contactRow}>
                <span className={styles.label}>邮箱：</span>
                <a href={`mailto:${email}`} className={styles.link}>{email}</a>
              </div>
              <div className={styles.contactRow}>
                <span className={styles.label}>地址：</span>
                <span className={styles.address}>{address}</span>
              </div>
            </div>
          </div>
        </div>

        {/* 右侧：应用下载（切图） */}
        <div className={styles.paymentIcons} aria-label="应用下载">
          <a
            className={styles.paymentIcon}
            href="https://play.google.com/store"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="在 Google Play 下载"
          >
            <img src="/assets/footer/google-play.png" alt="Google Play" />
          </a>
          <a
            className={styles.paymentIcon}
            href="https://apps.apple.com"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="在 App Store 下载"
          >
            <img src="/assets/footer/app-store.png" alt="App Store" />
          </a>
        </div>
      </div>

      {/* 版权信息 */}
      <div className={styles.copyright}>
        <p>© 版权所有 {currentYear}，ECBclub保留所有权利。</p>
      </div>
    </footer>
  );
}
